version: '3'

services:
  mc-players-web:
    build: 
      context: ./src/web/
      dockerfile: Dockerfile
    read_only: true
    container_name: mc-players-web
    restart: always
    cap_drop:
      - all
    security_opt:
      - no-new-privileges
    healthcheck:
      test: ["CMD-SHELL", "python3 healthcheck.py"]
      interval: 15s
      timeout: 3s
      retries: 2
    ports:
     - 2156:2156
    networks:
      - mc_players_internal
      - mc_players_external
    depends_on:
      mc-players-flag:
        condition: service_started

  mc-players-flag:
    build:
      context: ./src/flag/
      dockerfile: Dockerfile
    read_only: true
    container_name: mc-players-flag
    cap_drop:
      - all
    security_opt:
      - no-new-privileges
    networks:
      - mc_players_internal

networks:
  mc_players_internal:
    internal: true
  mc_players_external:
